### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Pepslee** [greensopinion/flutter-vector-map-tiles#127]
The problem with the example. I just run example but with my api_key

```
======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  CustomPaint CustomPaint:file:///home/peps/StudioProjects/flutter-vector-map-tiles/lib/src/grid/tile/delay_painter.dart:117:13
When the exception was thrown, this was the stack: 
#0      TextApproximation.renderer (package:vector_tile_renderer/src/features/text_renderer.dart:63:76)
#1      SymbolPointRenderer._preciselyOccupyLabelSpaceAtOffset (package:vector_tile_renderer/src/features/symbol_point_renderer.dart:89:22)
#2      SymbolPointRenderer._occupyLabelSpaceAtOffset (package:vector_tile_renderer/src/features/symbol_point_renderer.dart:80:12)
#3      SymbolPointRenderer.render (package:vector_tile_renderer/src/features/symbol_point_renderer.dart:56:12)
#4      FeatureDispatcher.render (package:vector_tile_renderer/src/features/feature_renderer.dart:49:16)
#5      DefaultLayer.render.<anonymous closure> (package:vector_tile_renderer/src/themes/theme_layers.dart:49:35)
#6      TileSpaceMapper.drawInTileSpace (package:vector_tile_renderer/src/features/tile_space_mapper.dart:39:7)
#7      DefaultLayer.render (package:vector_tile_renderer/src/themes/theme_layers.dart:47:31)
#8      Renderer.render.<anonymous closure> (package:vector_tile_renderer/src/renderer.dart:61:20)
#9      Timeline.timeSync (dart:developer/timeline.dart:166:22)
#10     profileSync (package:vector_tile_renderer/src/profiling.dart:16:19)
#11     Renderer.render (package:vector_tile_renderer/src/renderer.dart:38:5)
#12     VectorTilePainter.paint (package:vector_map_tiles/src/grid/tile/tile_painter.dart:50:10)
#13     _DelayCustomPainter.paint (package:vector_map_tiles/src/grid/tile/delay_painter.dart:164:17)
#14     RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:571:13)
#15     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:613:7)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#20     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#21     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#22     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1137:31)
#23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#29     _invoke (dart:ui/hooks.dart:145:13)
#30     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#31     _drawFrame (dart:ui/hooks.dart:112:31)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#551e8
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=155.9, h=155.9)
...  size: Size(155.9, 155.9)
...  painter: _DelayCustomPainter#09657()
RenderObject: RenderCustomPaint#551e8
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=155.9, h=155.9)
  size: Size(155.9, 155.9)
  painter: _DelayCustomPainter#09657()
====================================================================================================
```

**Comment by greensopinion** [comment]
Fixed in version 3.1.2 of [vector_tile_renderer](https://pub.dev/packages/vector_tile_renderer) dependency
