### ISSUE TITLE
InvalidProtocolBufferException: Protocol message tag had invalid wire type

### ISSUE THREAD

**Issue by eliabieri** [greensopinion/flutter-vector-map-tiles#50]
I'm using [tilemaker](https://github.com/systemed/tilemaker) to generate vector tiles from .pbf datasets that can be downloaded from [Geofabrik](https://download.geofabrik.de/europe.html).  
tilemaker claims to produce vector tiles in the Mapbox format, but the flutter_vector_map_tiles package does not seem to be able to parse them.  
Any ideas on how I could debug this?

#### Example vector tile generated by tilemaker

[example_vector_tile.zip](https://github.com/greensopinion/flutter-vector-map-tiles/files/8687005/example_vector_tile.zip)

#### Code

```dart
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:vector_map_tiles/vector_map_tiles.dart';
// ignore: depend_on_referenced_packages
import 'package:vector_tile_renderer/vector_tile_renderer.dart' show ProvidedThemes;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Vector Map',
      home: MapView(),
    );
  }
}

class MapView extends StatelessWidget {
  const MapView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => FlutterMap(
        options: MapOptions(
          center: LatLng(46.933849942685754, 7.424258598204977),
          zoom: 13.0,
          plugins: [
            VectorMapTilesPlugin(),
          ],
        ),
        layers: [
          VectorTileLayerOptions(
            theme: ProvidedThemes.lightTheme(),
            tileProviders: TileProviders({
              'openmaptiles': AssetTileVectorProvider(),
            }),
          ),
        ],
      );
}

class AssetTileVectorProvider extends VectorTileProvider {
  @override
  int get maximumZoom => 19;

  @override
  Future<Uint8List> provide(TileIdentity tile) {
    return rootBundle
        .load("assets/vector_tiles/${tile.z}_${tile.x}_${tile.y}.pbf")
        .then((value) => value.buffer.asUint8List());
  }
}

```

**Comment by FaFre** [comment]
Check if your layer is named corresponding to your configuration ''openmaptiles''. 

I never used tilemaker myself: Consult the documentation for the corresponding name. Or, if you get a style file, you can open it in maputnik to see the layer names. 

Elsewise you can set a breakpoint after the protobuf decode, to see the different layer names.

**Comment by greensopinion** [comment]
I've tried the example tile referenced in this issue with this test [vector_tile_reader_test.dart#L9](https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/test/src/vector_tile_reader_test.dart#L9) and it is read with no errors. Can you include the stack trace of the error you're seeing?

To troubleshoot, you might want to clone https://github.com/greensopinion/dart-vector-tile-renderer and try individual tiles in a unit test to replicate the issue.

To rule out the possibility of a problem with the way the tiles are loaded from the `rootBundle` perhaps try your application loading the same tiles from the filesystem instead.

**Comment by eliabieri** [comment]
First, thanks for taking the time to respond.  
tilemaker generates a metadata.json file that contains the names of the layers.  
For me, it has the following content:

```json
{
    "tilejson": "2.0.0",
    "scheme": "xyz",
    "type": "baselayer",
    "format": "pbf",
    "tiles": [
        "https://example.com/liechtenstein/{z}/{x}/{y}.pbf"
    ],
    "bounds": [
        5.952882,
        45.81617,
        10.49584,
        47.811260000000007
    ],
    "name": "Tilemaker to OpenMapTiles schema",
    "version": "3.0",
    "description": "Tile config based on OpenMapTiles schema",
    "minzoom": 0,
    "maxzoom": 14,
    "vector_layers": [
        {
            "id": "place",
            "fields": {
                "class": "String",
                "iso_a2": "String",
                "name:latin": "String",
                "rank": "Number"
            },
            "minzoom": 0,
            "maxzoom": 14
        },
        {
            "id": "boundary",
            "fields": {
                "admin_level": "Number",
                "disputed": "Number"
            },
            "minzoom": 0,
            "maxzoom": 14
        },
        {
            "id": "poi",
            "fields": {
                "class": "String",
                "name:latin": "String",
                "rank": "Number",
                "subclass": "String"
            },
            "minzoom": 12,
            "maxzoom": 14
        },
        {
            "id": "housenumber",
            "fields": {
                "housenumber": "String"
            },
            "minzoom": 14,
            "maxzoom": 14
        },
        {
            "id": "waterway",
            "fields": {
                "brunnel": "String",
                "class": "String",
                "intermittent": "Number",
                "name:latin": "String"
            },
            "minzoom": 8,
            "maxzoom": 14
        },
        {
            "id": "transportation",
            "fields": {
                "brunnel": "String",
                "class": "String",
                "oneway": "Number",
                "ramp": "Number",
                "service": "String"
            },
            "minzoom": 4,
            "maxzoom": 14
        },
        {
            "id": "transportation_name",
            "fields": {
                "class": "String",
                "name:latin": "String",
                "network": "String",
                "ref": "String",
                "ref_length": "Number"
            },
            "minzoom": 8,
            "maxzoom": 14
        },
        {
            "id": "building",
            "fields": {
                "housenumber": "String",
                "render_height": "Number",
                "render_min_height": "Number"
            },
            "minzoom": 13,
            "maxzoom": 14
        },
        {
            "id": "water",
            "fields": {
                "class": "String",
                "intermittent": "String"
            },
            "minzoom": 6,
            "maxzoom": 14
        },
        {
            "id": "water_name",
            "fields": {
                "class": "String",
                "name:latin": "String"
            },
            "minzoom": 14,
            "maxzoom": 14
        },
        {
            "id": "aeroway",
            "fields": {
                "class": "String",
                "ref": "String"
            },
            "minzoom": 11,
            "maxzoom": 14
        },
        {
            "id": "aerodrome_label",
            "fields": {
                "class": "String",
                "ele": "Number",
                "ele_ft": "Number",
                "iata": "String",
                "icao": "String",
                "name:latin": "String"
            },
            "minzoom": 10,
            "maxzoom": 14
        },
        {
            "id": "park",
            "fields": {
                "class": "String",
                "name:latin": "String"
            },
            "minzoom": 11,
            "maxzoom": 14
        },
        {
            "id": "landuse",
            "fields": {
                "class": "String",
                "name:latin": "String",
                "rank": "Number",
                "subclass": "String"
            },
            "minzoom": 4,
            "maxzoom": 14
        },
        {
            "id": "landcover",
            "fields": {
                "class": "String",
                "name:latin": "String",
                "rank": "Number",
                "subclass": "String"
            },
            "minzoom": 0,
            "maxzoom": 14
        },
        {
            "id": "mountain_peak",
            "fields": {
                "class": "String",
                "ele": "Number",
                "ele_ft": "Number",
                "name:latin": "String",
                "rank": "Number"
            },
            "minzoom": 11,
            "maxzoom": 14
        }
    ]
}
```

I've tried to change openmaptiles to one of the layers from above, but the behaviour hasn't changed. 
The following stack trace is the result:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: InvalidProtocolBufferException: Protocol message tag had invalid wire type.
#0      UnknownFieldSet.mergeFieldFromBuffer
package:protobuf/…/protobuf/unknown_field_set.dart:74
#1      _mergeFromCodedBufferReader
package:protobuf/…/protobuf/coded_buffer.dart:42
#2      GeneratedMessage.mergeFromBuffer
package:protobuf/…/protobuf/generated_message.dart:196
#3      new VectorTile.fromBuffer
package:vector_tile/…/proto/vector_tile.pb.dart:340
#4      VectorTile.fromBytes
package:vector_tile/vector_tile.dart:29
#5      VectorTileReader.read.<anonymous closure>
package:vector_tile_renderer/src/vector_tile_reader.dart:10
#6      Timeline.timeSync (dart:developer/timeline.dart:157:22)
#7      profileSync
package:vector_tile_renderer/src/profiling.dart:16
#8      VectorTileReader.read
package:vector_tile_renderer/src/vector_tile_reader.dart:9
#9      _createTile
package:vector_map_tiles/…/cache/vector_tile_loading_cache.dart:96
#10     _Job.apply
package:vector_map_tiles/…/executor/queue_executor.dart:96
#11     QueueExecutor._runOneAndReschedule
package:vector_map_tiles/…/executor/queue_executor.dart:51
#12     _rootRun (dart:async/zone.dart:1418:47)
#13     _CustomZone.run (dart:async/zone.dart:1328:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#16     _rootRun (dart:async/zone.dart:1426:13)
#17     _CustomZone.run (dart:async/zone.dart:1328:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

I then tried to adapt run the rendering_test from the [dart-vector-tile-renderer](https://github.com/greensopinion/dart-vector-tile-renderer) of @greensopinion but I'm getting the same error there:

```
00:01 +5 -1: loading /Users/eliabieri/Downloads/dart-vector-tile-renderer/test/benchmark/rendering_test.dart [E]
  Failed to load "/Users/eliabieri/Downloads/dart-vector-tile-renderer/test/benchmark/rendering_test.dart": Protocol message tag had invalid wire type.
  package:protobuf/src/protobuf/unknown_field_set.dart 74:9                                                              UnknownFieldSet.mergeFieldFromBuffer
  package:protobuf/src/protobuf/coded_buffer.dart 42:38                                                                  _mergeFromCodedBufferReader
  package:protobuf/src/protobuf/generated_message.dart 194:5                                                             GeneratedMessage.mergeFromBuffer
  package:vector_tile/raw/proto/vector_tile.pb.dart 340:128                                                              new VectorTile.fromBuffer
  package:vector_tile/vector_tile.dart 29:33                                                                             VectorTile.fromBytes
  package:vector_tile_renderer/src/vector_tile_reader.dart 10:25                                                         VectorTileReader.read.<fn>
  dart:developer                                                                                                         Timeline.timeSync
  package:vector_tile_renderer/src/profiling.dart 16:19                                                                  profileSync
  package:vector_tile_renderer/src/vector_tile_reader.dart 9:12                                                          VectorTileReader.read
  test/src/test_tile.dart 9:67                                                                                           readTestTile
  ===== asynchronous gap ===========================
  test/benchmark/rendering_test.dart 46:16                                                                               RenderPicture.setupAll
  ===== asynchronous gap ===========================
  test/benchmark/rendering_test.dart 77:3                                                                                main
  ===== asynchronous gap ===========================
  /var/folders/1g/plrmhyyx3vl78pfg2cvb4dx40000gn/T/flutter_tools.8rT7Kj/flutter_test_listener.dWDqJv/listener.dart 18:3  _testMain
```

Sadly, I'm kinda stuck with this.  
Should I use some other library to try to parse my .pbf files and verify, that they are indeed correctly generated?

I'm attaching some more [tiles](https://github.com/greensopinion/flutter-vector-map-tiles/files/8700704/tiles.zip) in case you're interested

**Comment by FaFre** [comment]
Mhm it seems like the features are divided into a lot of layers (@greensopinion this can maybe transformed into a performance improvement, by handling layers individually, like water, streets etc ... just an idea).

Right now the library awaits a single layer, containing all features, like its delivered via mapbox or stadia. You need to merge all those layers into one inside tilemaker, to make it consumeable by this library for now. Another option would be making this library ready for handling multiple layers.

**Comment by greensopinion** [comment]
> Should I use some other library to try to parse my .pbf files and verify, that they are indeed correctly generated?

sounds like a great idea!

> transformed into a performance improvement, by handling layers individually

Feel free to open a new issue to explore that idea.

**Comment by eliabieri** [comment]
I now configured tilemaker to generate only a single layer but the tiles are still rejected by the `vector_map_tiles` package with the same error.  
It's quite hard to debug as the error originates in the protobuf parser.  

[example_tile.pbf.zip](https://github.com/greensopinion/flutter-vector-map-tiles/files/8749828/example_tile.pbf.zip)

**Comment by FaFre** [comment]
Make sure tilemaker is using v2.1 of the vector tile spec.

Or, you can make sure that your pbf is valid, by writing a small test application using the standard .proto file https://github.com/mapbox/vector-tile-spec/tree/master/2.1 and the protobuf package https://pub.dev/packages/protobuf

**Comment by greensopinion** [comment]
closing, but feel free to reopen or comment if this continues to be an issue
