### ISSUE TITLE
Throw Invalid tile coordinates z=1,x=0,y=2 error with esri map

### ISSUE THREAD

**Issue by tashi146** [greensopinion/flutter-vector-map-tiles#56]
Hi I am tryin to load esri map using flutter-vector-map-tiles, I am using the same example code as well. But map is not rendering at all in application. It just show blank screen. Could you tell me what was the issue here.   
Code: 
```
import 'package:flutter/material.dart' as material;
import 'package:flutter/widgets.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:vector_map_tiles/vector_map_tiles.dart';
import 'package:vector_tile_renderer/vector_tile_renderer.dart';
import 'api_key.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({material.Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return material.MaterialApp(
      title: 'vector_map_tiles Example',
      theme: material.ThemeData.light(),
      home: const MyHomePage(title: 'vector_map_tiles Example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return material.Scaffold(
        appBar: material.AppBar(
          title: Text(widget.title),
        ),
        body: SafeArea(
            child: Column(children: [
          Flexible(
              child: FlutterMap(
            options: MapOptions(
                center: LatLng(12.925007, 77.593803),
                zoom: 2,
                maxZoom: 18,
                interactiveFlags: InteractiveFlag.drag |
                    InteractiveFlag.flingAnimation |
                    InteractiveFlag.pinchMove |
                    InteractiveFlag.pinchZoom |
                    InteractiveFlag.doubleTapZoom,
                plugins: [VectorMapTilesPlugin()]),
            layers: <LayerOptions>[
              // normally you would see TileLayerOptions which provides raster tiles
              // instead this vector tile layer replaces the standard tile layer
              VectorTileLayerOptions(
                  theme: _mapTheme(),
                  backgroundTheme: _backgroundTheme(),
                  // tileOffset: TileOffset.mapbox, enable with mapbox
                  tileProviders: TileProviders(
                      // Name must match name under "sources" in theme
                      {'esri': _cachingTileProvider(_urlTemplate())})),
            ],
          ))
        ])));
  }

  VectorTileProvider _cachingTileProvider(String urlTemplate) {
    return NetworkVectorTileProvider(
        urlTemplate: urlTemplate,
        // this is the maximum zoom of the provider, not the
        // maximum of the map. vector tiles are rendered
        // to larger sizes to support higher zoom levels
        maximumZoom: 18);
  }

  Theme _mapTheme() {
    // maps are rendered using themes
    // to provide a dark theme do something like this:
    // if (MediaQuery.of(context).platformBrightness == Brightness.dark) return myDarkTheme();
    return ProvidedThemes.lightTheme();
  }

  _backgroundTheme() {
    return _mapTheme()
        .copyWith(types: {ThemeLayerType.background, ThemeLayerType.fill});
  }

  String _urlTemplate() {
    // IMPORTANT: See readme about matching tile provider with theme

    // Stadia Maps source https://docs.stadiamaps.com/vector/
    return 'https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf?token=$apiKey';

    // Mapbox source https://docs.mapbox.com/api/maps/vector-tiles/#example-request-retrieve-vector-tiles
    // return 'https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/{z}/{x}/{y}.mvt?access_token=$mapboxApiKey',
  }
}
```   
**Output:**    
```
Blank screen with log:   
E/flutter (16275): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid tile coordinates z=1,x=0,y=2
E/flutter (16275): #0      NetworkVectorTileProvider.provide (package:vector_map_tiles/src/vector_tile_provider.dart:42:7)
E/flutter (16275): #1      VectorTileLoadingCache._loadBytes (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:85:44)
E/flutter (16275): <asynchronous suspension>
E/flutter (16275): #2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:65:15)
```

**Comment by husbycodereis** [comment]
The default TileProviders theme does not work with Esri VectorTileLayerOptions. In order to render Esri maps, you need to provide a custom theme such as:

```
Theme mapTheme(Map<String, dynamic> style, Set<ThemeLayerType>? mapTypes) {
    return ThemeReader(logger: null).read(style).copyWith(types: mapTypes);
  }
```

and inside the style parameter, you need to add the style.json file as a Map<String, dynamic>

This is the base arcgis / esri style json : https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/resources/styles/root.json

You can either get this as a response from a get request or create a .json file containing your whole styles JSON.

**Comment by hhkaos** [comment]
Thanks @husbycodereis, I was able to make it with your hints, here you can see the repo: https://github.com/hhkaos/flutter_arcgis_basemaps

@tashi146 I hope that helps.

@greensopinion do you want me to do a PR to this project to add another [Tiles provider](https://github.com/greensopinion/flutter-vector-map-tiles#themes-and-tile-providers) to the list?

**Comment by greensopinion** [comment]
Great to hear that you got it working!

> @greensopinion do you want me to do a PR to this project to add another [Tiles provider](https://github.com/greensopinion/flutter-vector-map-tiles#themes-and-tile-providers) to the list?

Sure, that would be great.

**Comment by hhkaos** [comment]
Great @greensopinion I will asap,

While I was refactoring [the repo](https://github.com/hhkaos/flutter_arcgis_basemaps) I noticed [some issues](https://github.com/hhkaos/flutter_arcgis_basemaps/issues/) displaying some map styles and labels. I guess I should fix at least the [labels thing](https://github.com/hhkaos/flutter_arcgis_basemaps/issues/1) before doing the PR.

Any hint would be appreciated. Thanks!! 😄

**Comment by greensopinion** [comment]
@hhkaos When I've seen issues like this before, it's usually because there are expressions in the theme that aren't supported by this library.

To troubleshoot the theme, consider adding a logger to the theme, e.g. `ThemeReader(Logger.console()).read(theme)`
You'll see warnings output to the console. If that's the case to fix it you'll either need to change your theme to only use supported expressions, or add support for the expressions you need to the renderer library (something like [this commit](https://github.com/greensopinion/dart-vector-tile-renderer/commit/882db86fd3e3eeb994189270bfe1f0e5e81c027a))

**Comment by hhkaos** [comment]
Awesome @greensopinion thanks! That's more than enough. 

I will check the stiles and try to add support for the expression to the renderer library 😄
