### ISSUE TITLE
Question: How to use MapTiler

### ISSUE THREAD

**Issue by komi1230** [greensopinion/flutter-vector-map-tiles#76]
Hello,

I'm trying to use this plugin to display MapTiler vector map with FlutterMap.
But the map isn't displayed properly.

My code is below:

<details><summary>code</summary>

```dart
FlutterMap(
  options: MapOptions(
    center: latlng.LatLng(latitude, longitude),
    zoom: 16.0,
    enableScrollWheel: true,
    enableMultiFingerGestureRace: false,
    interactiveFlags: InteractiveFlag.pinchMove |
        InteractiveFlag.drag |
        InteractiveFlag.pinchZoom,
    minZoom: 1,
    maxZoom: 20,
    plugins: [VectorMapTilesPlugin()],
  ),
  layers: [
    VectorTileLayerOptions(
      tileProviders: TileProviders({
        "openmaptiles": NetworkVectorTileProvider(
          urlTemplate:
              "https://api.maptiler.com/tiles/jp-mierune/{z}/{x}/{y}.pbf?key=${myKey}",
        ),
      }),
      theme: ProvidedThemes.lightTheme(),
    ),
  ],
),
```

</details>

And the error message is below:

<details><summary>error message</summary>

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
#0      CodedBufferReader.checkLastTagWas (package:protobuf/src/protobuf/coded_buffer_reader.dart:32:7)
#1      CodedBufferReader.readUnknownFieldSetGroup (package:protobuf/src/protobuf/coded_buffer_reader.dart:80:5)
#2      UnknownFieldSet.mergeFieldFromBuffer (package:protobuf/src/protobuf/unknown_field_set.dart:70:30)
#3      UnknownFieldSet.mergeFromCodedBufferReader (package:protobuf/src/protobuf/unknown_field_set.dart:87:24)
#4      CodedBufferReader.readUnknownFieldSetGroup (package:protobuf/src/protobuf/coded_buffer_reader.dart:79:21)
#5      UnknownFieldSet.mergeFieldFromBuffer (package:protobuf/src/protobuf/unknown_field_set.dart:70:30)
#6      _mergeFromCodedBufferReader (package:protobuf/src/protobuf/coded_buffer.dart:42:38)
#7      GeneratedMessage.mergeFromBuffer (package:protobuf/src/protobuf/generated_message.dart:185:5)
#8      new VectorTile.fromBuffer (package:vector_tile/raw/proto/vector_tile.pb.dart:340:128)
#9      VectorTile.fromBytes (package:vector_tile/vector_tile.dart:29:33)
#10     VectorTileReader.read.<anonymous closure> (package:vector_tile_renderer/src/vector_tile_reader.dart:10:25)
#11     Timeline.timeSync (dart:developer/timeline.dart:157:22)
#12     profileSync (package:vector_tile_renderer/src/profiling.dart:16:19)
#13     VectorTileReader.read (package:vector_tile_renderer/src/vector_tile_reader.dart:9:12)
#14     _createTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:101:44)
#15     _Job.apply (package:vector_map_tiles/src/executor/queue_executor.dart:96:59)
#16     QueueExecutor._runOneAndReschedule (package:vector_map_tiles/src/executor/queue_executor.dart:51:34)
#17     _rootRun (dart:async/zone.dart:1418:47)
#18     _CustomZone.run (dart:async/zone.dart:1328:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#21     _rootRun (dart:async/zone.dart:1426:13)
#22     _CustomZone.run (dart:async/zone.dart:1328:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

</details>

If you have any clue, I'm very happy to hear that.

**Comment by komi1230** [comment]
I found my bug was caused by `zoom` field.
When I unset this, map has been displayed correctly.

This issue has been resolved, so I'm closing.

**Comment by dptorres** [comment]
@komi1230 Hi I'm just starting with Maptiler, just want to know where you got your urlTemplate? Thanks!

**Comment by komi1230** [comment]
@dptorres Actually this issue was not resolved. After displayed, the map would be crashed with scrolling or swiping.

In the beginning of starting app, the map is correctly displayed with adjusting zoom level. In my case, zoom level was too high. 
But just it was.

Finally I gave up using FlutterMap. Now I'm using Google Maps.

I'm sorry I cannot help to resolve your issue.

**Comment by greensopinion** [comment]
@komi1230 sorry to hear that you couldn't get it working. If you have steps to reproduce the crash that would be really helpful.

@dptorres feel free to open an issue with the specifics of your problem

**Comment by greensopinion** [comment]
Great to hear! Thanks for the explanation.
